# =========================================================
# Generated by Bangla Syntax Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

n = int(5)
ফ্যাক্টরিয়াল = int(1)
i = int(1)
while (i <= n):
    ফ্যাক্টরিয়াল = (ফ্যাক্টরিয়াল * i)
    i = (i + 1)

print("৫ এর ফ্যাক্টরিয়াল:")
print(ফ্যাক্টরিয়াল)
