# =========================================================
# Generated by Bangla Syntax Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

সীমা = int(10)
যোগফল = int(0)
i = int(1)
while (i <= সীমা):
    যোগফল = (যোগফল + i)
    i = (i + 1)

print("১ থেকে ১০ এর যোগফল:")
print(যোগফল)
