# =========================================================
# Generated by Bangla Syntax Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

pi = float(3.1416)
ত্রিজ্যা = float(5.5)
ক্ষেত্রফল = float(((pi * ত্রিজ্যা) * ত্রিজ্যা))
print("বৃত্তের ক্ষেত্রফল:")
print(ক্ষেত্রফল)
