# =========================================================
# Generated by Bangla Syntax Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

a = int(10)
b = int(5)
c = int(2)
ফল = int((a + (b * c)))
print("গণনার ফল:")
print(ফল)
