# =========================================================
# Generated by Bangla Syntax Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

a = int(10)
b = int(25)
tmp = int(a)
a = b
b = tmp
print("পরিবর্তনের পরে a:")
print(a)
print("পরিবর্তনের পরে b:")
print(b)
